wip - use typing.get_{args,origin} instead of custom functions
todo: replacement
todo: use test case

In [6]: @dataclass(frozen=True)
   ...: class Ad:
   ...:     a: int
   ...:

In [7]: @dataclass(frozen=True)
   ...: class Bd:
   ...:     b: str
   ...:

In [8]: @dataclass(frozen=True)
   ...: class Cd:
   ...:     a: Union[Ad,Bd]

   ...: In [8]: @dataclass(frozen=True)
   ...:    ...: class Cd:
   ...:    ...:     a: Union[Ad,Bd, List[Ad]]
   ...:
   ...:

In [7]: deserialize(Cd, serialize(Cd(Bd('a'))))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/dev/env/miniconda3/envs/parsing/lib/python3.8/site-packages/core_utils/serialization.py in _values_for_type(field_name_expected_type, data, type_data, custom)
    492             if value is not None:
--> 493                 yield deserialize(field_type, value, custom)  # type: ignore
    494             else:

~/dev/env/miniconda3/envs/parsing/lib/python3.8/site-packages/core_utils/serialization.py in deserialize(type_value, value, custom)
    162
--> 163     elif issubclass(checking_type_value, Mapping):
    164         k_type, v_type = type_value.__args__  # type: ignore

~/dev/env/miniconda3/envs/parsing/lib/python3.8/typing.py in __subclasscheck__(self, cls)
    773             if not isinstance(cls, _GenericAlias):
--> 774                 return issubclass(cls, self.__origin__)
    775             if cls._special:

~/dev/env/miniconda3/envs/parsing/lib/python3.8/abc.py in __subclasscheck__(cls, subclass)
    101             """Override for issubclass(subclass, cls)."""
--> 102             return _abc_subclasscheck(cls, subclass)
    103

TypeError: issubclass() arg 1 must be a class

The above exception was the direct cause of the following exception:

FieldDeserializeFail                      Traceback (most recent call last)
<ipython-input-7-11e9782aaf15> in <module>
----> 1 deserialize(Cd, serialize(Cd(Bd('a'))))

~/dev/env/miniconda3/envs/parsing/lib/python3.8/site-packages/core_utils/serialization.py in deserialize(type_value, value, custom)
    138
    139     elif is_dataclass(checking_type_value):
--> 140         return _dataclass_from_dict(type_value, value, custom)
    141
    142     # NOTE: Need to have type_value instead of checking_type_value here !

~/dev/env/miniconda3/envs/parsing/lib/python3.8/site-packages/core_utils/serialization.py in _dataclass_from_dict(dataclass_type, data, custom)
    315             field_and_types, data, dataclass_type, custom
    316         )
--> 317         deserialized_fields = list(deserialized_fields)
    318         field_values = dict(
    319             zip(map(lambda x: x[0], field_and_types), deserialized_fields)

~/dev/env/miniconda3/envs/parsing/lib/python3.8/site-packages/core_utils/serialization.py in _values_for_type(field_name_expected_type, data, type_data, custom)
    497             raise
    498         except Exception as e:
--> 499             raise FieldDeserializeFail(
    500                 field_name=field_name, expected_type=field_type, actual_value=value
    501             ) from e

FieldDeserializeFail: Expecting field 'a' to have type 'typing.Union[__main__.Ad, __main__.Bd, typing.List[__main__.Ad]]'. Instead, found value '{'b': 'a'}', which has incorrect type 'dict'. Caused by error: 'issubclass() arg 1 must be a class'